/**
 * Pure JavaScript Client-Side PDF 1.4 Generator
 * Compliant with Salesforce Lightning Locker / LWS (Zero external dependencies)
 */

function escapePdfText(str) {
    if (!str) return '';
    return String(str)
        .replace(/\\/g, '\\\\')
        .replace(/\(/g, '\\(')
        .replace(/\)/g, '\\)')
        .replace(/[\r\n]+/g, ' ');
}

/**
 * Truncates text to fit within specified character width approximation
 */
function fitText(text, maxChars) {
    const s = String(text || '');
    if (s.length <= maxChars) return s;
    return s.substring(0, maxChars - 2) + '..';
}

export function generatePdfBlob(config) {
    const {
        title = 'Salesforce Records Report',
        objectLabel = 'Records',
        orientation = 'landscape', // 'landscape' or 'portrait'
        columns = [],
        records = [],
        userInfo = {},
        scopeLabel = 'My Records',
        rowsPerPage = 15 // Default to 15 records per page!
    } = config;

    // Dimensions in points (72 points = 1 inch)
    const isLandscape = orientation.toLowerCase() === 'landscape';
    const pageWidth = isLandscape ? 792 : 612;
    const pageHeight = isLandscape ? 612 : 792;

    const margin = 36; // 0.5 inch margin
    const contentWidth = pageWidth - (margin * 2);

    // Calculate column widths
    const colCount = Math.max(columns.length, 1);
    const colWidth = Math.floor(contentWidth / colCount);

    const rowHeight = 22;
    const tableHeaderHeight = 26;

    // Pagination based on user-defined rowsPerPage (e.g. 15 per page)
    const effectiveRowsPerPage = Math.max(1, parseInt(rowsPerPage, 10) || 15);

    // Split records across pages strictly by user-defined rowsPerPage
    const pagesData = [];
    if (records.length === 0) {
        pagesData.push([]);
    } else {
        let currentIdx = 0;
        while (currentIdx < records.length) {
            pagesData.push(records.slice(currentIdx, currentIdx + effectiveRowsPerPage));
            currentIdx += effectiveRowsPerPage;
        }
    }

    const totalPages = pagesData.length;
    const exportDate = new Date().toLocaleString();

    // Build PDF content streams for each page
    const pageStreams = [];

    pagesData.forEach((pageRecords, pageIndex) => {
        const isFirstPage = pageIndex === 0;
        let stream = '';

        // Helper to add drawing/text
        function drawRect(x, y, w, h, r, g, b, isFill = true) {
            stream += `${(r/255).toFixed(3)} ${(g/255).toFixed(3)} ${(b/255).toFixed(3)} ${isFill ? 'rg' : 'RG'}\n`;
            stream += `${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re ${isFill ? 'f' : 's'}\n`;
        }

        function drawLine(x1, y1, x2, y2, r = 200, g = 200, b = 200, lineWidth = 0.5) {
            stream += `${lineWidth} w\n`;
            stream += `${(r/255).toFixed(3)} ${(g/255).toFixed(3)} ${(b/255).toFixed(3)} RG\n`;
            stream += `${x1.toFixed(2)} ${y1.toFixed(2)} m ${x2.toFixed(2)} ${y2.toFixed(2)} l S\n`;
        }

        function drawText(font, size, x, y, text, r = 0, g = 0, b = 0) {
            stream += `BT\n`;
            stream += `/${font} ${size} Tf\n`;
            stream += `${(r/255).toFixed(3)} ${(g/255).toFixed(3)} ${(b/255).toFixed(3)} rg\n`;
            stream += `${x.toFixed(2)} ${y.toFixed(2)} Td\n`;
            stream += `(${escapePdfText(text)}) Tj\n`;
            stream += `ET\n`;
        }

        let currentY = pageHeight - margin;

        if (isFirstPage) {
            // Header Top Bar: Deep Salesforce Blue
            drawRect(margin, currentY - 42, contentWidth, 42, 1, 118, 211, true);

            // Document Title in bold white
            drawText('F2', 15, margin + 14, currentY - 26, title, 255, 255, 255);
            drawText('F1', 9, margin + 14, currentY - 37, `${objectLabel.toUpperCase()} REPORT | SCOPE: ${scopeLabel.toUpperCase()} | TOTAL RECORDS: ${records.length} (${effectiveRowsPerPage} PER PAGE)`, 220, 235, 250);

            // Metadata card background
            drawRect(margin, currentY - 96, contentWidth, 50, 248, 250, 252, true);
            drawRect(margin, currentY - 96, contentWidth, 50, 203, 213, 225, false);

            // Metadata columns
            const col1X = margin + 14;
            const col2X = margin + Math.floor(contentWidth * 0.45);
            const col3X = margin + Math.floor(contentWidth * 0.75);

            drawText('F2', 8, col1X, currentY - 60, 'GENERATED BY:', 100, 116, 139);
            drawText('F1', 9, col1X, currentY - 73, `${userInfo.name || 'Salesforce User'} (${userInfo.profileName || 'User'})`, 30, 41, 59);
            drawText('F1', 8, col1X, currentY - 86, `${userInfo.email || ''}`, 71, 85, 105);

            drawText('F2', 8, col2X, currentY - 60, 'ORGANIZATION:', 100, 116, 139);
            drawText('F1', 9, col2X, currentY - 73, `${userInfo.orgName || userInfo.companyName || 'Salesforce'}`, 30, 41, 59);
            drawText('F1', 8, col2X, currentY - 86, `Export Scope: ${scopeLabel}`, 71, 85, 105);

            drawText('F2', 8, col3X, currentY - 60, 'EXPORT DATE & TIME:', 100, 116, 139);
            drawText('F1', 9, col3X, currentY - 73, exportDate, 30, 41, 59);
            drawText('F2', 8, col3X, currentY - 86, `Rows in Export: ${records.length} (Page ${pageIndex + 1} of ${totalPages})`, 1, 118, 211);

            currentY -= 108;
        } else {
            // Subsequent page mini header
            drawRect(margin, currentY - 28, contentWidth, 28, 241, 245, 249, true);
            drawText('F2', 10, margin + 12, currentY - 18, `${title} - ${objectLabel} (Page ${pageIndex + 1} of ${totalPages})`, 11, 31, 58);
            drawText('F1', 8, margin + contentWidth - 170, currentY - 18, `Exported: ${exportDate}`, 100, 116, 139);
            currentY -= 38;
        }

        const tableStartY = currentY;

        // Table Header
        drawRect(margin, currentY - tableHeaderHeight, contentWidth, tableHeaderHeight, 15, 39, 68, true); // Dark navy header

        const approxCharsPerCol = Math.max(10, Math.floor(colWidth / 5.8));

        columns.forEach((col, cIdx) => {
            const cellX = margin + (cIdx * colWidth);
            drawText('F2', 8, cellX + 6, currentY - 16, fitText(col.label, approxCharsPerCol), 255, 255, 255);
        });

        currentY -= tableHeaderHeight;

        // Table Rows
        if (pageRecords.length === 0) {
            drawRect(margin, currentY - rowHeight, contentWidth, rowHeight, 255, 255, 255, true);
            drawText('F1', 9, margin + 20, currentY - 14, 'No records found matching criteria.', 100, 116, 139);
            currentY -= rowHeight;
        } else {
            pageRecords.forEach((record, rIdx) => {
                const isEven = rIdx % 2 === 0;
                // Alternating row colors
                if (isEven) {
                    drawRect(margin, currentY - rowHeight, contentWidth, rowHeight, 255, 255, 255, true);
                } else {
                    drawRect(margin, currentY - rowHeight, contentWidth, rowHeight, 248, 250, 252, true);
                }

                // Row bottom border
                drawLine(margin, currentY - rowHeight, margin + contentWidth, currentY - rowHeight, 226, 232, 240, 0.5);

                // Row Cells
                columns.forEach((col, cIdx) => {
                    const cellX = margin + (cIdx * colWidth);
                    let val = record[col.fieldName];

                    // Formatting numbers/currency
                    if (val === null || val === undefined || val === '') {
                        val = '-';
                    } else if (col.type === 'currency' && typeof val === 'number') {
                        val = '$' + val.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 2 });
                    }

                    const formattedText = fitText(val, approxCharsPerCol);
                    drawText('F1', 8, cellX + 6, currentY - 14, formattedText, 30, 41, 59);
                });

                currentY -= rowHeight;
            });
        }

        // Table outer borders
        drawLine(margin, currentY, margin, tableStartY, 203, 213, 225, 0.5);
        drawLine(margin + contentWidth, currentY, margin + contentWidth, tableStartY, 203, 213, 225, 0.5);

        // Page Footer
        drawLine(margin, margin + 16, margin + contentWidth, margin + 16, 203, 213, 225, 0.5);
        drawText('F1', 8, margin, margin + 5, `Confidential - Internal Salesforce Document | Exported by ${userInfo.name || 'User'} | Multi-Page v2.0`, 148, 163, 184);
        const pageText = `Page ${pageIndex + 1} of ${totalPages} (${pageRecords.length} records on this page)`;
        drawText('F2', 8, margin + contentWidth - 170, margin + 5, pageText, 100, 116, 139);

        pageStreams.push(stream);
    });

    // Assemble the complete PDF 1.4 document
    const objects = [];
    let currentObjId = 1;

    // Obj 1: Catalog
    const catalogId = currentObjId++;
    // Obj 2: Pages
    const pagesId = currentObjId++;
    // Font F1 (Helvetica)
    const fontF1Id = currentObjId++;
    // Font F2 (Helvetica-Bold)
    const fontF2Id = currentObjId++;

    const pageObjectIds = [];
    const streamObjectIds = [];

    // Assign IDs for pages and streams
    pagesData.forEach(() => {
        pageObjectIds.push(currentObjId++);
        streamObjectIds.push(currentObjId++);
    });

    let pdf = '%PDF-1.4\n%\xE2\xE3\xCF\xD3\n';
    const xrefOffsets = [];

    function recordOffset() {
        xrefOffsets.push(pdf.length);
    }

    // 1: Catalog
    recordOffset();
    pdf += `${catalogId} 0 obj\n<< /Type /Catalog /Pages ${pagesId} 0 R >>\nendobj\n`;

    // 2: Pages
    recordOffset();
    const kidsStr = pageObjectIds.map(id => `${id} 0 R`).join(' ');
    pdf += `${pagesId} 0 obj\n<< /Type /Pages /Kids [${kidsStr}] /Count ${totalPages} >>\nendobj\n`;

    // 3: Font F1
    recordOffset();
    pdf += `${fontF1Id} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj\n`;

    // 4: Font F2
    recordOffset();
    pdf += `${fontF2Id} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>\nendobj\n`;

    // Pages and Streams
    pagesData.forEach((_, idx) => {
        const pageId = pageObjectIds[idx];
        const streamId = streamObjectIds[idx];
        const streamContent = pageStreams[idx];

        // Page Object
        recordOffset();
        pdf += `${pageId} 0 obj\n<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Contents ${streamId} 0 R /Resources << /Font << /F1 ${fontF1Id} 0 R /F2 ${fontF2Id} 0 R >> >> >>\nendobj\n`;

        // Content Stream Object
        recordOffset();
        pdf += `${streamId} 0 obj\n<< /Length ${streamContent.length} >>\nstream\n${streamContent}\nendstream\nendobj\n`;
    });

    // Cross-Reference Table
    const startXref = pdf.length;
    pdf += `xref\n0 ${currentObjId}\n`;
    pdf += `0000000000 65535 f \r\n`;

    xrefOffsets.forEach(offset => {
        const offsetStr = String(offset).padStart(10, '0');
        pdf += `${offsetStr} 00000 n \r\n`;
    });

    // Trailer
    pdf += `trailer\n<< /Size ${currentObjId} /Root ${catalogId} 0 R >>\nstartxref\n${startXref}\n%%EOF\n`;

    // Convert string to Uint8Array for binary-safe Blob creation
    const buffer = new Uint8Array(pdf.length);
    for (let i = 0; i < pdf.length; i++) {
        buffer[i] = pdf.charCodeAt(i) & 0xff;
    }

    return new Blob([buffer], { type: 'application/pdf' });
}

/**
 * Trigger immediate browser file download
 */
export function downloadBlobAsFile(blob, filename) {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename || 'Salesforce_Export.pdf';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    setTimeout(() => {
        URL.revokeObjectURL(url);
    }, 1500);
}
