/**
 * Pure JavaScript Client-Side PDF 1.4 Generator
 * Compliant with Salesforce Lightning Locker / LWS (Zero external dependencies)
 */

function escapePdfText(str) {
  if (!str) return "";
  return String(str)
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/[\r\n]+/g, " ");
}

/**
 * Truncates text to fit within specified character width approximation
 */
function fitText(text, maxChars) {
  const s = String(text || "");
  if (s.length <= maxChars) return s;
  return s.substring(0, maxChars - 2) + "..";
}

export function generatePdfBlob(config) {
  const {
    title = "Salesforce Records Report",
    objectLabel = "Records",
    orientation = "landscape", // 'landscape' or 'portrait'
    columns = [],
    records = [],
    userInfo = {},
    scopeLabel = "My Records",
    rowsPerPage = 15 // Default to 15 records per page!
  } = config;

  // Dimensions in points (72 points = 1 inch)
  const isLandscape = orientation.toLowerCase() === "landscape";
  const pageWidth = isLandscape ? 792 : 612;
  const pageHeight = isLandscape ? 612 : 792;

  const margin = 36; // 0.5 inch margin
  const contentWidth = pageWidth - margin * 2;

  // Calculate column widths
  const colCount = Math.max(columns.length, 1);
  const colWidth = Math.floor(contentWidth / colCount);

  const rowHeight = 22;
  const tableHeaderHeight = 26;

  // Pagination based on user-defined rowsPerPage (e.g. 15 per page)
  const effectiveRowsPerPage = Math.max(1, parseInt(rowsPerPage, 10) || 15);

  // Split records across pages strictly by user-defined rowsPerPage
  const pagesData = [];
  if (records.length === 0) {
    pagesData.push([]);
  } else {
    let currentIdx = 0;
    while (currentIdx < records.length) {
      pagesData.push(
        records.slice(currentIdx, currentIdx + effectiveRowsPerPage)
      );
      currentIdx += effectiveRowsPerPage;
    }
  }

  const totalPages = pagesData.length;
  const exportDate = new Date().toLocaleString();

  // Build PDF content streams for each page
  const pageStreams = [];

  pagesData.forEach((pageRecords, pageIndex) => {
    const isFirstPage = pageIndex === 0;
    let stream = "";

    // Helper to add drawing/text
    function drawRect(x, y, w, h, r, g, b, isFill = true) {
      stream += `${(r / 255).toFixed(3)} ${(g / 255).toFixed(3)} ${(b / 255).toFixed(3)} ${isFill ? "rg" : "RG"}\n`;
      stream += `${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re ${isFill ? "f" : "s"}\n`;
    }

    function drawLine(
      x1,
      y1,
      x2,
      y2,
      r = 200,
      g = 200,
      b = 200,
      lineWidth = 0.5
    ) {
      stream += `${lineWidth} w\n`;
      stream += `${(r / 255).toFixed(3)} ${(g / 255).toFixed(3)} ${(b / 255).toFixed(3)} RG\n`;
      stream += `${x1.toFixed(2)} ${y1.toFixed(2)} m ${x2.toFixed(2)} ${y2.toFixed(2)} l S\n`;
    }

    function drawText(font, size, x, y, text, r = 0, g = 0, b = 0) {
      stream += `BT\n`;
      stream += `/${font} ${size} Tf\n`;
      stream += `${(r / 255).toFixed(3)} ${(g / 255).toFixed(3)} ${(b / 255).toFixed(3)} rg\n`;
      stream += `${x.toFixed(2)} ${y.toFixed(2)} Td\n`;
      stream += `(${escapePdfText(text)}) Tj\n`;
      stream += `ET\n`;
    }

    let currentY = pageHeight - margin;

    if (isFirstPage) {
      // Header Top Bar: Deep Salesforce Blue
      drawRect(margin, currentY - 42, contentWidth, 42, 1, 118, 211, true);

      // Document Title in bold white
      drawText("F2", 15, margin + 14, currentY - 26, title, 255, 255, 255);
      drawText(
        "F1",
        9,
        margin + 14,
        currentY - 37,
        `${objectLabel.toUpperCase()} REPORT | SCOPE: ${scopeLabel.toUpperCase()} | TOTAL RECORDS: ${records.length} (${effectiveRowsPerPage} PER PAGE)`,
        220,
        235,
        250
      );

      // Metadata card background
      drawRect(margin, currentY - 96, contentWidth, 50, 248, 250, 252, true);
      drawRect(margin, currentY - 96, contentWidth, 50, 203, 213, 225, false);

      // Metadata columns
      const col1X = margin + 14;
      const col2X = margin + Math.floor(contentWidth * 0.45);
      const col3X = margin + Math.floor(contentWidth * 0.75);

      drawText("F2", 8, col1X, currentY - 60, "GENERATED BY:", 100, 116, 139);
      drawText(
        "F1",
        9,
        col1X,
        currentY - 73,
        `${userInfo.name || "Salesforce User"} (${userInfo.profileName || "User"})`,
        30,
        41,
        59
      );
      drawText(
        "F1",
        8,
        col1X,
        currentY - 86,
        `${userInfo.email || ""}`,
        71,
        85,
        105
      );

      drawText("F2", 8, col2X, currentY - 60, "ORGANIZATION:", 100, 116, 139);
      drawText(
        "F1",
        9,
        col2X,
        currentY - 73,
        `${userInfo.orgName || userInfo.companyName || "Salesforce"}`,
        30,
        41,
        59
      );
      drawText(
        "F1",
        8,
        col2X,
        currentY - 86,
        `Export Scope: ${scopeLabel}`,
        71,
        85,
        105
      );

      drawText(
        "F2",
        8,
        col3X,
        currentY - 60,
        "EXPORT DATE & TIME:",
        100,
        116,
        139
      );
      drawText("F1", 9, col3X, currentY - 73, exportDate, 30, 41, 59);
      drawText(
        "F2",
        8,
        col3X,
        currentY - 86,
        `Rows in Export: ${records.length} (Page ${pageIndex + 1} of ${totalPages})`,
        1,
        118,
        211
      );

      currentY -= 108;
    } else {
      // Subsequent page mini header
      drawRect(margin, currentY - 28, contentWidth, 28, 241, 245, 249, true);
      drawText(
        "F2",
        10,
        margin + 12,
        currentY - 18,
        `${title} - ${objectLabel} (Page ${pageIndex + 1} of ${totalPages})`,
        11,
        31,
        58
      );
      drawText(
        "F1",
        8,
        margin + contentWidth - 170,
        currentY - 18,
        `Exported: ${exportDate}`,
        100,
        116,
        139
      );
      currentY -= 38;
    }

    const tableStartY = currentY;

    // Table Header
    drawRect(
      margin,
      currentY - tableHeaderHeight,
      contentWidth,
      tableHeaderHeight,
      15,
      39,
      68,
      true
    ); // Dark navy header

    const approxCharsPerCol = Math.max(10, Math.floor(colWidth / 5.8));

    columns.forEach((col, cIdx) => {
      const cellX = margin + cIdx * colWidth;
      drawText(
        "F2",
        8,
        cellX + 6,
        currentY - 16,
        fitText(col.label, approxCharsPerCol),
        255,
        255,
        255
      );
    });

    currentY -= tableHeaderHeight;

    // Table Rows
    if (pageRecords.length === 0) {
      drawRect(
        margin,
        currentY - rowHeight,
        contentWidth,
        rowHeight,
        255,
        255,
        255,
        true
      );
      drawText(
        "F1",
        9,
        margin + 20,
        currentY - 14,
        "No records found matching criteria.",
        100,
        116,
        139
      );
      currentY -= rowHeight;
    } else {
      pageRecords.forEach((record, rIdx) => {
        const isEven = rIdx % 2 === 0;
        // Alternating row colors
        if (isEven) {
          drawRect(
            margin,
            currentY - rowHeight,
            contentWidth,
            rowHeight,
            255,
            255,
            255,
            true
          );
        } else {
          drawRect(
            margin,
            currentY - rowHeight,
            contentWidth,
            rowHeight,
            248,
            250,
            252,
            true
          );
        }

        // Row bottom border
        drawLine(
          margin,
          currentY - rowHeight,
          margin + contentWidth,
          currentY - rowHeight,
          226,
          232,
          240,
          0.5
        );

        // Row Cells
        columns.forEach((col, cIdx) => {
          const cellX = margin + cIdx * colWidth;
          let val = record[col.fieldName];

          // Formatting numbers/currency
          if (val === null || val === undefined || val === "") {
            val = "-";
          } else if (col.type === "currency" && typeof val === "number") {
            val =
              "$" +
              val.toLocaleString("en-US", {
                minimumFractionDigits: 0,
                maximumFractionDigits: 2
              });
          }

          const formattedText = fitText(val, approxCharsPerCol);
          drawText(
            "F1",
            8,
            cellX + 6,
            currentY - 14,
            formattedText,
            30,
            41,
            59
          );
        });

        currentY -= rowHeight;
      });
    }

    // Table outer borders
    drawLine(margin, currentY, margin, tableStartY, 203, 213, 225, 0.5);
    drawLine(
      margin + contentWidth,
      currentY,
      margin + contentWidth,
      tableStartY,
      203,
      213,
      225,
      0.5
    );

    // Page Footer
    drawLine(
      margin,
      margin + 16,
      margin + contentWidth,
      margin + 16,
      203,
      213,
      225,
      0.5
    );
    drawText(
      "F1",
      8,
      margin,
      margin + 5,
      `Confidential - Internal Salesforce Document | Exported by ${userInfo.name || "User"} | Multi-Page v2.0`,
      148,
      163,
      184
    );
    const pageText = `Page ${pageIndex + 1} of ${totalPages} (${pageRecords.length} records on this page)`;
    drawText(
      "F2",
      8,
      margin + contentWidth - 170,
      margin + 5,
      pageText,
      100,
      116,
      139
    );

    pageStreams.push(stream);
  });

  // Assemble the complete PDF 1.4 document
  let currentObjId = 1;

  // Obj 1: Catalog
  const catalogId = currentObjId++;
  // Obj 2: Pages
  const pagesId = currentObjId++;
  // Font F1 (Helvetica)
  const fontF1Id = currentObjId++;
  // Font F2 (Helvetica-Bold)
  const fontF2Id = currentObjId++;

  const pageObjectIds = [];
  const streamObjectIds = [];

  // Assign IDs for pages and streams
  pagesData.forEach(() => {
    pageObjectIds.push(currentObjId++);
    streamObjectIds.push(currentObjId++);
  });

  let pdf = "%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";
  const xrefOffsets = [];

  function recordOffset() {
    xrefOffsets.push(pdf.length);
  }

  // 1: Catalog
  recordOffset();
  pdf += `${catalogId} 0 obj\n<< /Type /Catalog /Pages ${pagesId} 0 R >>\nendobj\n`;

  // 2: Pages
  recordOffset();
  const kidsStr = pageObjectIds.map((id) => `${id} 0 R`).join(" ");
  pdf += `${pagesId} 0 obj\n<< /Type /Pages /Kids [${kidsStr}] /Count ${totalPages} >>\nendobj\n`;

  // 3: Font F1
  recordOffset();
  pdf += `${fontF1Id} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj\n`;

  // 4: Font F2
  recordOffset();
  pdf += `${fontF2Id} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>\nendobj\n`;

  // Pages and Streams
  pagesData.forEach((_, idx) => {
    const pageId = pageObjectIds[idx];
    const streamId = streamObjectIds[idx];
    const streamContent = pageStreams[idx];

    // Page Object
    recordOffset();
    pdf += `${pageId} 0 obj\n<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Contents ${streamId} 0 R /Resources << /Font << /F1 ${fontF1Id} 0 R /F2 ${fontF2Id} 0 R >> >> >>\nendobj\n`;

    // Content Stream Object
    recordOffset();
    pdf += `${streamId} 0 obj\n<< /Length ${streamContent.length} >>\nstream\n${streamContent}\nendstream\nendobj\n`;
  });

  // Cross-Reference Table
  const startXref = pdf.length;
  pdf += `xref\n0 ${currentObjId}\n`;
  pdf += `0000000000 65535 f \r\n`;

  xrefOffsets.forEach((offset) => {
    const offsetStr = String(offset).padStart(10, "0");
    pdf += `${offsetStr} 00000 n \r\n`;
  });

  // Trailer
  pdf += `trailer\n<< /Size ${currentObjId} /Root ${catalogId} 0 R >>\nstartxref\n${startXref}\n%%EOF\n`;

  // Convert string to Uint8Array for binary-safe Blob creation
  const buffer = new Uint8Array(pdf.length);
  for (let i = 0; i < pdf.length; i++) {
    buffer[i] = pdf.charCodeAt(i) & 0xff;
  }

  return new Blob([buffer], { type: "application/pdf" });
}

/**
 * Pure JavaScript Client-Side CSV Generator
 * Compliant with RFC 4180 and Microsoft Excel UTF-8 BOM
 */
export function generateCsvBlob(columns = [], records = []) {
  function escapeCsvValue(val) {
    if (val === null || val === undefined) return "";
    const str = String(val);
    if (
      str.includes(",") ||
      str.includes('"') ||
      str.includes("\n") ||
      str.includes("\r")
    ) {
      return '"' + str.replace(/"/g, '""') + '"';
    }
    return str;
  }

  // 1. Header row with active column labels
  const headers = columns
    .map((c) => escapeCsvValue(c.label || c.fieldName))
    .join(",");

  // 2. Data rows with values matching column fieldNames
  const rows = records.map((record) => {
    return columns
      .map((col) => {
        const val = record[col.fieldName];
        return escapeCsvValue(val);
      })
      .join(",");
  });

  // 3. Prepend \uFEFF Byte Order Mark for Excel UTF-8 compatibility
  const csvContent = "\uFEFF" + [headers, ...rows].join("\r\n");
  return new Blob([csvContent], { type: "application/octet-stream" });
}

/**
 * Pure JavaScript Client-Side OpenXML XLSX Generator
 * Produces native Microsoft Excel .xlsx workbooks with zero external dependencies.
 */
const CRC_TABLE = new Uint32Array(256);
for (let i = 0; i < 256; i++) {
  let c = i;
  for (let k = 0; k < 8; k++) {
    c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  }
  CRC_TABLE[i] = c;
}

function crc32(bytes) {
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) {
    crc = CRC_TABLE[(crc ^ bytes[i]) & 0xff] ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function getColumnLetter(colIndex) {
  let letter = "";
  let temp = colIndex + 1;
  while (temp > 0) {
    const mod = (temp - 1) % 26;
    letter = String.fromCharCode(65 + mod) + letter;
    temp = Math.floor((temp - mod) / 26);
  }
  return letter;
}

function escapeXml(str) {
  if (str === null || str === undefined) return "";
  return String(str)
    .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g, "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function buildZip(files) {
  const encoder = new TextEncoder();
  const fileEntries = files.map((f) => {
    const nameBytes = encoder.encode(f.name);
    const dataBytes =
      typeof f.data === "string" ? encoder.encode(f.data) : f.data;
    const crc = crc32(dataBytes);
    return {
      nameBytes,
      dataBytes,
      crc,
      size: dataBytes.length
    };
  });

  const dosTime = 0x0000;
  const dosDate = 0x5c21; // 2026-01-01

  let totalSize = 0;
  for (const entry of fileEntries) {
    totalSize += 30 + entry.nameBytes.length + entry.size;
    totalSize += 46 + entry.nameBytes.length;
  }
  totalSize += 22;

  const buffer = new Uint8Array(totalSize);
  const view = new DataView(buffer.buffer);
  let localOffset = 0;
  const centralEntries = [];

  for (const entry of fileEntries) {
    const headerOffset = localOffset;

    view.setUint32(localOffset, 0x04034b50, true);
    view.setUint16(localOffset + 4, 20, true);
    view.setUint16(localOffset + 6, 0x0800, true);
    view.setUint16(localOffset + 8, 0, true);
    view.setUint16(localOffset + 10, dosTime, true);
    view.setUint16(localOffset + 12, dosDate, true);
    view.setUint32(localOffset + 14, entry.crc, true);
    view.setUint32(localOffset + 18, entry.size, true);
    view.setUint32(localOffset + 22, entry.size, true);
    view.setUint16(localOffset + 26, entry.nameBytes.length, true);
    view.setUint16(localOffset + 28, 0, true);

    buffer.set(entry.nameBytes, localOffset + 30);
    buffer.set(entry.dataBytes, localOffset + 30 + entry.nameBytes.length);

    localOffset += 30 + entry.nameBytes.length + entry.size;

    centralEntries.push({
      entry,
      headerOffset
    });
  }

  const centralDirStart = localOffset;

  for (const { entry, headerOffset } of centralEntries) {
    view.setUint32(localOffset, 0x02014b50, true);
    view.setUint16(localOffset + 4, 20, true);
    view.setUint16(localOffset + 6, 20, true);
    view.setUint16(localOffset + 8, 0x0800, true);
    view.setUint16(localOffset + 10, 0, true);
    view.setUint16(localOffset + 12, dosTime, true);
    view.setUint16(localOffset + 14, dosDate, true);
    view.setUint32(localOffset + 16, entry.crc, true);
    view.setUint32(localOffset + 20, entry.size, true);
    view.setUint32(localOffset + 24, entry.size, true);
    view.setUint16(localOffset + 28, entry.nameBytes.length, true);
    view.setUint16(localOffset + 30, 0, true);
    view.setUint16(localOffset + 32, 0, true);
    view.setUint16(localOffset + 34, 0, true);
    view.setUint16(localOffset + 36, 0, true);
    view.setUint32(localOffset + 38, 0, true);
    view.setUint32(localOffset + 42, headerOffset, true);

    buffer.set(entry.nameBytes, localOffset + 46);
    localOffset += 46 + entry.nameBytes.length;
  }

  const centralDirSize = localOffset - centralDirStart;

  view.setUint32(localOffset, 0x06054b50, true);
  view.setUint16(localOffset + 4, 0, true);
  view.setUint16(localOffset + 6, 0, true);
  view.setUint16(localOffset + 8, centralEntries.length, true);
  view.setUint16(localOffset + 10, centralEntries.length, true);
  view.setUint32(localOffset + 12, centralDirSize, true);
  view.setUint32(localOffset + 16, centralDirStart, true);
  view.setUint16(localOffset + 20, 0, true);

  return buffer;
}

export function generateXlsxBlob(
  columns = [],
  records = [],
  sheetName = "Report"
) {
  const cleanSheetName =
    (sheetName || "Report")
      .replace(/[*?:/\\\[\]]/g, "")
      .substring(0, 31) || "Report";

  const contentTypesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
  <Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
</Types>`;

  const rootRelsXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>`;

  const wbRelsXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>`;

  const workbookXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets>
    <sheet name="${escapeXml(cleanSheetName)}" sheetId="1" r:id="rId1"/>
  </sheets>
</workbook>`;

  const stylesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <fonts count="2">
    <font><sz val="11"/><color rgb="FF1E293B"/><name val="Calibri"/></font>
    <font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font>
  </fonts>
  <fills count="3">
    <fill><patternFill patternType="none"/></fill>
    <fill><patternFill patternType="gray125"/></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FF0176D3"/></patternFill></fill>
  </fills>
  <borders count="2">
    <border><left/><right/><top/><bottom/><diagonal/></border>
    <border>
      <left style="thin"><color rgb="FFE2E8F0"/></left>
      <right style="thin"><color rgb="FFE2E8F0"/></right>
      <top style="thin"><color rgb="FFE2E8F0"/></top>
      <bottom style="thin"><color rgb="FFE2E8F0"/></bottom>
    </border>
  </borders>
  <cellStyleXfs count="1">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0"/>
  </cellStyleXfs>
  <cellXfs count="3">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
    <xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1"/>
    <xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1"/>
  </cellXfs>
</styleSheet>`;

  // Calculate approximate column widths based on label and data values
  let colsXml = "<cols>";
  columns.forEach((col, idx) => {
    let maxLen = (col.label || col.fieldName || "").length;
    const sampleLimit = Math.min(records.length, 50);
    for (let i = 0; i < sampleLimit; i++) {
      const val = records[i][col.fieldName];
      if (val !== null && val !== undefined) {
        maxLen = Math.max(maxLen, String(val).length);
      }
    }
    const width = Math.min(60, Math.max(12, maxLen + 3));
    colsXml += `<col min="${idx + 1}" max="${idx + 1}" width="${width}" customWidth="1"/>`;
  });
  colsXml += "</cols>";

  // Build Sheet1 XML rows
  let sheetRows = "";

  // 1. Header row
  let headerCells = "";
  columns.forEach((col, colIdx) => {
    const cellRef = `${getColumnLetter(colIdx)}1`;
    const label = escapeXml(col.label || col.fieldName || "");
    headerCells += `<c r="${cellRef}" s="1" t="inlineStr"><is><t>${label}</t></is></c>`;
  });
  sheetRows += `<row r="1" ht="24" customHeight="1">${headerCells}</row>`;

  // 2. Data rows
  records.forEach((record, rowIdx) => {
    const rowNum = rowIdx + 2;
    let dataCells = "";
    columns.forEach((col, colIdx) => {
      const cellRef = `${getColumnLetter(colIdx)}${rowNum}`;
      const val = record[col.fieldName];
      if (val === null || val === undefined || val === "") {
        return;
      }
      if (typeof val === "number" && !isNaN(val)) {
        dataCells += `<c r="${cellRef}" s="2"><v>${val}</v></c>`;
      } else if (typeof val === "boolean") {
        dataCells += `<c r="${cellRef}" s="2" t="b"><v>${val ? 1 : 0}</v></c>`;
      } else {
        const strVal = escapeXml(val);
        dataCells += `<c r="${cellRef}" s="2" t="inlineStr"><is><t xml:space="preserve">${strVal}</t></is></c>`;
      }
    });
    sheetRows += `<row r="${rowNum}" ht="20" customHeight="1">${dataCells}</row>`;
  });

  const sheetXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  ${colsXml}
  <sheetData>${sheetRows}</sheetData>
</worksheet>`;

  const zipBuffer = buildZip([
    { name: "[Content_Types].xml", data: contentTypesXml },
    { name: "_rels/.rels", data: rootRelsXml },
    { name: "xl/_rels/workbook.xml.rels", data: wbRelsXml },
    { name: "xl/workbook.xml", data: workbookXml },
    { name: "xl/styles.xml", data: stylesXml },
    { name: "xl/worksheets/sheet1.xml", data: sheetXml }
  ]);

  return new Blob([zipBuffer], {
    type: "application/octet-stream"
  });
}

/**
 * Trigger immediate browser file download
 */
export function downloadBlobAsFile(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename || "Salesforce_Export.pdf";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  // eslint-disable-next-line @lwc/lwc/no-async-operation
  setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 1500);
}